In [1]:
from tensorflow import keras
print(keras.__version__)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-pac


Original exception was:
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance

3.9.2


In [15]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report

In [16]:
# 1. Cargar y preparar los datos
iris = load_iris()
X = iris.data
y = iris.target

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
y_cat = to_categorical(y)  # One-hot encoding para salida

In [7]:
# Escalado de características
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2, random_state=42)


In [14]:
import keras

In [8]:
# 2. Definir el modelo con Keras
model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)),  # Capa oculta con 10 neuronas y ReLU
    Dense(3, activation='softmax')                   # Capa de salida para 3 clases
])


C:\ProgramData\Anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
# 3. Compilar el modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [10]:
# 4. Entrenar
model.fit(X_train, y_train, epochs=100, verbose=1, validation_data=(X_test, y_test))



Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 75ms/step - accuracy: 0.3471 - loss: 1.1733 - val_accuracy: 0.3000 - val_loss: 1.1915
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3271 - loss: 1.1679 - val_accuracy: 0.2667 - val_loss: 1.1632
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3550 - loss: 1.1014 - val_accuracy: 0.2667 - val_loss: 1.1363
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2942 - loss: 1.1255 - val_accuracy: 0.2333 - val_loss: 1.1100
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3254 - loss: 1.0744 - val_accuracy: 0.2333 - val_loss: 1.0848
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3173 - loss: 1.0616 - val_accuracy: 0.2333 - val_loss: 1.0599
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3083 - loss: 1.0166 - val_accuracy: 0.2333 - val_loss: 1.0364
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3738 - loss: 0.9883 - val_accuracy: 0.3000 - val_loss:

Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8231 - loss: 0.4991 - val_accuracy: 0.8667 - val_loss: 0.5339
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7690 - loss: 0.5369 - val_accuracy: 0.8667 - val_loss: 0.5291
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7398 - loss: 0.5427 - val_accuracy: 0.8667 - val_loss: 0.5244
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7679 - loss: 0.5324 - val_accuracy: 0.8667 - val_loss: 0.5198
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7794 - loss: 0.5196 - val_accuracy: 0.8667 - val_loss: 0.5153
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7892 - loss: 0.5354 - val_accuracy: 0.8667 - val_loss: 0.5110
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8017 - loss: 0.5168 - val_accuracy: 0.8667 - val_loss: 0.5067
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7352 - loss: 0.5438 - val_accuracy: 0.8667 - v

In [11]:
# 5. Evaluar
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

print("\n🔎 Reporte de clasificación:")
print(classification_report(y_true, y_pred_classes, target_names=iris.target_names))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

🔎 Reporte de clasificación:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.56      0.71         9
   virginica       0.73      1.00      0.85        11

    accuracy                           0.87        30
   macro avg       0.91      0.85      0.85        30
weighted avg       0.90      0.87      0.86        30



In [12]:
y_pred

array([[0.04727051, 0.41801193, 0.53471756],
       [0.959261  , 0.02648619, 0.01425277],
       [0.00196115, 0.18851534, 0.8095235 ],
       [0.06059113, 0.40660968, 0.5327991 ],
       [0.02919956, 0.29855266, 0.6722478 ],
       [0.94788086, 0.04239387, 0.00972527],
       [0.20659027, 0.54828244, 0.2451273 ],
       [0.0312617 , 0.2691762 , 0.69956213],
       [0.00778407, 0.5387298 , 0.45348614],
       [0.08615679, 0.5897511 , 0.32409203],
       [0.05468391, 0.31725076, 0.6280653 ],
       [0.936222  , 0.06077671, 0.00300134],
       [0.9614897 , 0.0309983 , 0.00751199],
       [0.9502914 , 0.04642383, 0.00328478],
       [0.9845821 , 0.01239812, 0.00301978],
       [0.13537705, 0.31539622, 0.54922676],
       [0.02185389, 0.32417324, 0.6539729 ],
       [0.06543957, 0.736686  , 0.1978744 ],
       [0.06714202, 0.5345389 , 0.3983191 ],
       [0.01491579, 0.35921267, 0.6258716 ],
       [0.96869564, 0.02917478, 0.00212957],
       [0.05464338, 0.3797748 , 0.56558174],
       [0.

In [13]:
y_pred_classes

array([2, 0, 2, 2, 2, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])